---
abstract: 'Generates flickr-like navigation links'
author:
  - 'Masayoshi Sekimura <sekimura@cpan.org>'
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Page-FlickrLike
no_index:
  directory:
    - inc
    - t
requires:
  Data::Page: 0
  Exporter::Lite: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.02
